### ISSUE TITLE
Creating universal fallback fonts

### ISSUE THREAD

**Issue by bdon** [maplibre/font-maker#16]
The current version of font-maker is good at converting custom fonts for a single language, but global map use cases need multilingual fallbacks, ideally covering as much of basic Unicode as possible.

Discussed in MapLibre eastern call: https://github.com/maplibre/maplibre/discussions/154

Some font options are:
* Arial Unicode MS (Licensing ??)
* Noto / Source
* DejaVu

The existing solutions are to find SDF font stacks somewhere, but there isn't an up-to-date reproducible way to build these universal font stacks.

We need to:
* If web is a viable way to build a universal fontstack, it needs to be fast enough. It is currently way slower than the command line version for unknown reasons. See #14 
* Write some scripts against a Noto checkout or other that generates a universal fontstack using the command line tool from multiple individual script files. A starting point for this is https://github.com/maplibre/font-maker/tree/main/examples . Or is there a "mega-Noto TTF" somewhere?
* The generated fontstack name should be an input option instead of auto-generating based on FreeType data.

**Comment by bdon** [comment]
* Option to ignore CJK glyph ranges
* Related to https://github.com/maplibre/maplibre-gl-js/issues/1051 with adjustment of `top`
* Related to https://github.com/maplibre/maplibre-gl-js/issues/2990

**Comment by bdon** [comment]
Build using a downloaded copy of https://github.com/notofonts/notofonts.github.io

**Comment by neodescis** [comment]
I was scrounging for the Noto universal font and stumbled on this. It would be great if Font Maker could do this. I'm not sure if it's helpful, but I did manage to find this repo that is supposed to be able to combine the multiple Noto Sans fonts, but I couldn't get it to build:

https://github.com/openmaptiles/fonts

**Comment by bdon** [comment]
@neodescis you can download a Noto build based on the code here at Releases:

https://github.com/maplibre/font-maker/releases

**Comment by bdon** [comment]
I'm going to close this issue in favor of scripts and committed font glyphs in https://github.com/protomaps/basemaps-assets, for a couple reasons:

* Recognition that all simple codepoint -> glyph mappings are opinionated and no universal font is going to work for all MapLibre users, languages and scripts. Just as MapLibre GL is not opinionated about the particular layers and tags in tiles, font-maker shouldn't be opinionated about fontstack names or choice of Arabic variant scripts. That will happen in a downstream repo at https://github.com/protomaps/basemaps-assets
* Having a dedicated assets repo means we can serve glyphs through the GitHub CDN, and we don't need to clutter another repo with hundreds of files. 
* Downloading a zip file of the entire contents is simple and obvious with a dedicated assets repo, as opposed to needing to make GitHub releases manually. 

cc @ChrisLoer @pnorman
